In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)
%matplotlib inline

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df=pd.read_csv("drive/My Drive/Notebooks/data/job_postings.csv")

In [4]:
df

,job_id,company_id,title,description,max_salary,med_salary,min_salary,pay_period,formatted_work_type,location,...,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type
0,85008768,NaN,Licensed Insurance Agent,While many industries were hurt by the last fe...,52000.0,NaN,45760.0,YEARLY,Full-time,"Chico, CA",...,1708301126000,NaN,NaN,NaN,1692749193000,NaN,1,FULL_TIME,USD,BASE_SALARY
1,133114754,77766802.0,Sales Manager,Are you a dynamic and creative marketing profe...,NaN,NaN,NaN,NaN,Full-time,"Santa Clarita, CA",...,1695426553000,NaN,NaN,NaN,1692834553000,NaN,0,FULL_TIME,NaN,NaN
2,133196985,1089558.0,Model Risk Auditor,Join Us as a Model Risk Auditor â€“ Showcase You...,NaN,NaN,NaN,NaN,Contract,"New York, NY",...,1695321872000,NaN,NaN,NaN,1692729872000,NaN,0,CONTRACT,NaN,NaN
3,381055942,96654609.0,Business Manager,Business ManagerFirst Baptist Church ForneyFor...,NaN,NaN,NaN,NaN,Full-time,"Forney, TX",...,1695424007000,NaN,NaN,NaN,1692832007000,NaN,0,FULL_TIME,NaN,NaN
4,529257371,1244539.0,NY Studio Assistant,YOU COULD BE ONE OF THE MAGIC MAKERS\nKen Fulk...,NaN,NaN,NaN,NaN,Full-time,"New York, NY",...,1708419602000,NaN,NaN,NaN,1692867714000,NaN,1,FULL_TIME,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15881,3701373516,74718032.0,Sanitation Technician,"Location:\n\nWest Columbia, SC, US, 29172\n\n2...",NaN,NaN,NaN,NaN,Part-time,"West Columbia, SC",...,1695336734000,NaN,Entry level,NaN,1692744734000,aspirebakeriescareers.com,0,PART_TIME,NaN,NaN
15882,3701373522,38897.0,Unit Secretary,Job Title: Unit Secretary\nDepartment: Nursing...,NaN,NaN,NaN,NaN,Full-time,"Teaneck, NJ",...,1695336368000,NaN,Entry level,NaN,1692744368000,recruiting.ultipro.com,0,FULL_TIME,NaN,NaN
15883,3701373523,38897.0,"Radiology Aide, Perdiem","Job Title: Radiology Aide, Perdiem\nDepartment...",NaN,NaN,NaN,NaN,Part-time,"Teaneck, NJ",...,1695336368000,NaN,Entry level,NaN,1692744368000,recruiting.ultipro.com,0,PART_TIME,NaN,NaN
15884,3701373524,2623.0,MRI Manager,Grade 105\nJob Type: Officer of Administration...,135000.0,NaN,110000.0,YEARLY,Full-time,"New York, NY",...,1695336071000,NaN,Mid-Senior level,NaN,1692744071000,opportunities.columbia.edu,0,FULL_TIME,USD,BASE_SALARY
15885,3701373527,84659.0,Area Director of Business Development,Nexion Health Management affiliates operate 56...,NaN,NaN,NaN,NaN,Full-time,"Vicksburg, MS",...,1695335131000,NaN,NaN,NaN,1692743131000,NaN,0,FULL_TIME,NaN,NaN

In [5]:
df.columns

Index(['job_id', 'company_id', 'title', 'description', 'max_salary',
       'med_salary', 'min_salary', 'pay_period', 'formatted_work_type',
       'location', 'applies', 'original_listed_time', 'remote_allowed',
       'views', 'job_posting_url', 'application_url', 'application_type',
       'expiry', 'closed_time', 'formatted_experience_level', 'skills_desc',
       'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type'],
      dtype='object')

In [6]:
df.shape

(15886, 27)

In [7]:
df.info

<bound method DataFrame.info of            job_id  company_id                                  title  \
0        85008768         NaN               Licensed Insurance Agent
1       133114754  77766802.0                          Sales Manager
2       133196985   1089558.0                     Model Risk Auditor
3       381055942  96654609.0                       Business Manager
4       529257371   1244539.0                    NY Studio Assistant
...           ...         ...                                    ...
15881  3701373516  74718032.0                  Sanitation Technician
15882  3701373522     38897.0                         Unit Secretary
15883  3701373523     38897.0                Radiology Aide, Perdiem
15884  3701373524      2623.0                            MRI Manager
15885  3701373527     84659.0  Area Director of Business Development

                                             description  max_salary  \
0      While many industries were hurt by the last fe...     52000.0
1      Are you a dynamic and creative marketing profe...         NaN
2      Join Us as a Model Risk Auditor â€“ Showcase You...         NaN
3      Business ManagerFirst Baptist Church ForneyFor...         NaN
4      YOU COULD BE ONE OF THE MAGIC MAKERS\nKen Fulk...         NaN
...                                                  ...         ...
15881  Location:\n\nWest Columbia, SC, US, 29172\n\n2...         NaN
15882  Job Title: Unit Secretary\nDepartment: Nursing...         NaN
15883  Job Title: Radiology Aide, Perdiem\nDepartment...         NaN
15884  Grade 105\nJob Type: Officer of Administration...    135000.0
15885  Nexion Health Management affiliates operate 56...         NaN

       med_salary  min_salary pay_period formatted_work_type  \
0             NaN     45760.0     YEARLY           Full-time
1             NaN         NaN        NaN           Full-time
2             NaN         NaN        NaN            Contract
3             NaN         NaN        NaN           Full-time
4             NaN         NaN        NaN           Full-time
...           ...         ...        ...                 ...
15881         NaN         NaN        NaN           Part-time
15882         NaN         NaN        NaN           Full-time
15883         NaN         NaN        NaN           Part-time
15884         NaN    110000.0     YEARLY           Full-time
15885         NaN         NaN        NaN           Full-time

                location  ...         expiry  closed_time  \
0              Chico, CA  ...  1708301126000          NaN
1      Santa Clarita, CA  ...  1695426553000          NaN
2           New York, NY  ...  1695321872000          NaN
3             Forney, TX  ...  1695424007000          NaN
4           New York, NY  ...  1708419602000          NaN
...                  ...  ...            ...          ...
15881  West Columbia, SC  ...  1695336734000          NaN
15882        Teaneck, NJ  ...  1695336368000          NaN
15883        Teaneck, NJ  ...  1695336368000          NaN
15884       New York, NY  ...  1695336071000          NaN
15885      Vicksburg, MS  ...  1695335131000          NaN

       formatted_experience_level  skills_desc    listed_time  \
0                             NaN          NaN  1692749193000
1                             NaN          NaN  1692834553000
2                             NaN          NaN  1692729872000
3                             NaN          NaN  1692832007000
4                             NaN          NaN  1692867714000
...                           ...          ...            ...
15881                 Entry level          NaN  1692744734000
15882                 Entry level          NaN  1692744368000
15883                 Entry level          NaN  1692744368000
15884            Mid-Senior level          NaN  1692744071000
15885                         NaN          NaN  1692743131000

                   posting_domain sponsored  work_type  currency  \
0                             NaN         1  FULL_TIME       USD
1                             NaN         0  FULL_TIME       NaN
2                             NaN         0   CONTRACT       NaN
3                             NaN         0  FULL_TIME       NaN
4                             NaN         1  FULL_TIME       NaN
...                           ...       ...        ...       ...
15881   aspirebakeriescareers.com         0  PART_TIME       NaN
15882      recruiting.ultipro.com         0  FULL_TIME       NaN
15883      recruiting.ultipro.com         0  PART_TIME       NaN
15884  opportunities.columbia.edu         0  FULL_TIME       USD
15885                         NaN         0  FULL_TIME       NaN

      compensation_type
0           BASE_SALARY
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
15881               NaN
15882               NaN
15883               NaN
15884       BASE_SALARY
15885               NaN

[15886 rows x 27 columns]>

In [8]:
df[[ 'title', 'min_salary', 'location']]

                                       title  min_salary           location
0                   Licensed Insurance Agent     45760.0          Chico, CA
1                              Sales Manager         NaN  Santa Clarita, CA
2                         Model Risk Auditor         NaN       New York, NY
3                           Business Manager         NaN         Forney, TX
4                        NY Studio Assistant         NaN       New York, NY
...                                      ...         ...                ...
15881                  Sanitation Technician         NaN  West Columbia, SC
15882                         Unit Secretary         NaN        Teaneck, NJ
15883                Radiology Aide, Perdiem         NaN        Teaneck, NJ
15884                            MRI Manager    110000.0       New York, NY
15885  Area Director of Business Development         NaN      Vicksburg, MS

[15886 rows x 3 columns]

In [9]:
df2=df[[ 'title', 'min_salary', 'location']]
df2

                                       title  min_salary           location
0                   Licensed Insurance Agent     45760.0          Chico, CA
1                              Sales Manager         NaN  Santa Clarita, CA
2                         Model Risk Auditor         NaN       New York, NY
3                           Business Manager         NaN         Forney, TX
4                        NY Studio Assistant         NaN       New York, NY
...                                      ...         ...                ...
15881                  Sanitation Technician         NaN  West Columbia, SC
15882                         Unit Secretary         NaN        Teaneck, NJ
15883                Radiology Aide, Perdiem         NaN        Teaneck, NJ
15884                            MRI Manager    110000.0       New York, NY
15885  Area Director of Business Development         NaN      Vicksburg, MS

[15886 rows x 3 columns]

In [10]:
df2.shape

(15886, 3)

In [11]:
df2.loc[(df2['title']=="Sales Associate")]

                 title  min_salary           location
641    Sales Associate         NaN    Maple Grove, MN
1876   Sales Associate         NaN     Morgantown, WV
1877   Sales Associate         NaN      Strasburg, VA
2310   Sales Associate         NaN     Scottsdale, AZ
4048   Sales Associate         NaN  Daytona Beach, FL
...                ...         ...                ...
15249  Sales Associate        13.5        Atlanta, GA
15294  Sales Associate         NaN       Whittier, CA
15317  Sales Associate         NaN       Whittier, CA
15320  Sales Associate         NaN          Chino, CA
15343  Sales Associate        13.5     Pittsburgh, PA

[64 rows x 3 columns]

In [12]:
df3 = df2.loc[(df2['title']=="Sales Associate")]

In [13]:
df3

                 title  min_salary           location
641    Sales Associate         NaN    Maple Grove, MN
1876   Sales Associate         NaN     Morgantown, WV
1877   Sales Associate         NaN      Strasburg, VA
2310   Sales Associate         NaN     Scottsdale, AZ
4048   Sales Associate         NaN  Daytona Beach, FL
...                ...         ...                ...
15249  Sales Associate        13.5        Atlanta, GA
15294  Sales Associate         NaN       Whittier, CA
15317  Sales Associate         NaN       Whittier, CA
15320  Sales Associate         NaN          Chino, CA
15343  Sales Associate        13.5     Pittsburgh, PA

[64 rows x 3 columns]

In [14]:
df3.shape

(64, 3)

In [15]:
(df3['min_salary'].isnull().sum())

54

In [16]:
df3.info(all)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 64 entries, 641 to 15343
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       64 non-null     object
 1   min_salary  10 non-null     float64
 2   location    64 non-null     object
dtypes: float64(1), object(2)
memory usage: 2.0+ KB

54 divided by 192*100=28.125% is the percentage of missing salary values in this datafreme

In [17]:
df3.dropna(subset=['min_salary'], inplace=True)

<ipython-input-17-0cbe464a1672>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.dropna(subset=['min_salary'], inplace=True)

In [18]:
df3

                 title  min_salary                      location
5006   Sales Associate        20.0                    Boston, MA
6387   Sales Associate     50000.0                   Seattle, WA
6551   Sales Associate     50000.0    Miami-Fort Lauderdale Area
6911   Sales Associate        17.0             Redondo Beach, CA
11151  Sales Associate     50000.0                   Raleigh, NC
11259  Sales Associate     50000.0                   Chicago, IL
11401  Sales Associate     50000.0  Washington DC-Baltimore Area
11423  Sales Associate     50000.0                   Phoenix, AZ
15249  Sales Associate        13.5                   Atlanta, GA
15343  Sales Associate        13.5                Pittsburgh, PA

In [19]:
df3.loc[(df3['min_salary']>20000)]

                 title  min_salary                      location
6387   Sales Associate     50000.0                   Seattle, WA
6551   Sales Associate     50000.0    Miami-Fort Lauderdale Area
11151  Sales Associate     50000.0                   Raleigh, NC
11259  Sales Associate     50000.0                   Chicago, IL
11401  Sales Associate     50000.0  Washington DC-Baltimore Area
11423  Sales Associate     50000.0                   Phoenix, AZ

In [20]:
df4=df3.loc[(df3['min_salary']>20000)]

In [21]:
df4

                 title  min_salary                      location
6387   Sales Associate     50000.0                   Seattle, WA
6551   Sales Associate     50000.0    Miami-Fort Lauderdale Area
11151  Sales Associate     50000.0                   Raleigh, NC
11259  Sales Associate     50000.0                   Chicago, IL
11401  Sales Associate     50000.0  Washington DC-Baltimore Area
11423  Sales Associate     50000.0                   Phoenix, AZ

In [25]:
df4.drop([6387,6551,11259,11401,11423])

                 title  min_salary     location
11151  Sales Associate     50000.0  Raleigh, NC