In [2]:
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df=pd.read_csv("drive/My Drive/Notebooks/data/travel_tourism_dataset.csv")

In [5]:
df

,Trip #no.,Duration,Cost of Travel(Entire Trip),Mode of Travel,Stay,First Name,Last Name,Date of Birth,Address,Age,Sex,Nationality,Date of Travel
0,55,1,20111,Flight,Hotel,Cristina,Fuentes,1914-06-14,"5143 Pope Camp Apt. 028\nLake Emily, UT 71371",74,Non-Binary,Lao People's Democratic Republic,2022-09-13
1,288,5,29681,Car,Hotel,Patricia,Young,1923-09-25,716 Dominguez Row Suite 775\nSouth Tiffanyboro...,19,Female,Gabon,2021-09-04
2,291,7,24950,Flight,Airbnb,Christina,Kirby,1935-01-02,"PSC 4600, Box 1237\nAPO AE 32510",36,Female,Syrian Arab Republic,2021-01-25
3,131,19,18676,Roadtrip,Airbnb,Michael,Hudson,1982-04-21,"7013 Bryant Club Suite 695\nSouth Tina, WI 26739",38,Non-Binary,Afghanistan,2022-01-28
4,281,28,18899,Flight,Airbnb,Francisco,Hensley,1913-06-29,"074 Scott Brook Suite 700\nLukeville, VA 46541",38,Non-Binary,Uruguay,2021-10-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,142,24,17801,Roadtrip,Resorts,Kerry,Allen,2002-06-02,"93471 Joyce Courts Apt. 859\nMitchellside, OK ...",73,Non-Binary,Mali,2023-07-03
2996,265,16,23410,Train,Hotel,Kevin,Johnson,1916-07-28,"921 Katie Parkways Apt. 558\nWest Lawrence, CT...",50,Male,Mexico,2022-08-22
2997,232,22,5656,Roadtrip,Hotel,William,Mclaughlin,1917-07-25,"99384 Shirley Pine Apt. 439\nEast Angela, ND 1...",36,Non-Binary,American Samoa,2021-02-08
2998,112,15,27509,Car,Airbnb,Marcus,Ray,1962-07-07,"PSC 1488, Box 2535\nAPO AP 58905",48,Female,Jersey,2021-06-19
2999,283,13,19865,Cruise,Airbnb,Tom,Fletcher,1990-03-20,908 Christina Junctions Apt. 546\nPerkinsville...,22,Non-Binary,Mozambique,2021-08-07

In [6]:
df.shape

(3000, 13)

In [7]:
df.columns

Index(['Trip #no.', 'Duration', 'Cost of Travel(Entire Trip)',
       'Mode of Travel', 'Stay', 'First Name', 'Last Name', 'Date of Birth',
       'Address', 'Age', 'Sex', 'Nationality', 'Date of Travel'],
      dtype='object')

In [8]:
df['Age']

0       74
1       19
2       36
3       38
4       38
        ..
2995    73
2996    50
2997    36
2998    48
2999    22
Name: Age, Length: 3000, dtype: int64

In [9]:
df['Stay']

0         Hotel
1         Hotel
2        Airbnb
3        Airbnb
4        Airbnb
         ...
2995    Resorts
2996      Hotel
2997      Hotel
2998     Airbnb
2999     Airbnb
Name: Stay, Length: 3000, dtype: object

In [10]:
df['Cost of Travel(Entire Trip)']

0       20111
1       29681
2       24950
3       18676
4       18899
        ...
2995    17801
2996    23410
2997     5656
2998    27509
2999    19865
Name: Cost of Travel(Entire Trip), Length: 3000, dtype: int64

In [11]:
df['First Name']

0        Cristina
1        Patricia
2       Christina
3         Michael
4       Francisco
          ...
2995        Kerry
2996        Kevin
2997      William
2998       Marcus
2999          Tom
Name: First Name, Length: 3000, dtype: object

In [12]:
df['Last Name']

0          Fuentes
1            Young
2            Kirby
3           Hudson
4          Hensley
           ...
2995         Allen
2996       Johnson
2997    Mclaughlin
2998           Ray
2999      Fletcher
Name: Last Name, Length: 3000, dtype: object

In [13]:
df.loc[df['Age']<30]

,Trip #no.,Duration,Cost of Travel(Entire Trip),Mode of Travel,Stay,First Name,Last Name,Date of Birth,Address,Age,Sex,Nationality,Date of Travel
1,288,5,29681,Car,Hotel,Patricia,Young,1923-09-25,716 Dominguez Row Suite 775\nSouth Tiffanyboro...,19,Female,Gabon,2021-09-04
6,173,8,16642,Flight,Airbnb,Debra,Mitchell,1927-02-17,"05543 Scott Mount Suite 815\nPriceland, VI 56675",25,Male,San Marino,2022-08-07
8,154,27,25299,Car,Airbnb,Jeffrey,Key,1913-02-13,"4725 Ferguson Hill Suite 157\nEriktown, PR 09538",25,Female,Kyrgyz Republic,2022-06-28
18,7,19,25750,Roadtrip,Other,Lisa,Smith,1993-09-19,Unit 7905 Box 2194\nDPO AE 84402,22,Transgender,France,2021-12-15
22,56,24,10551,Flight,Resorts,John,Johnson,1922-11-04,"43152 Deborah Pine Suite 123\nWest Andreland, ...",19,Transgender,Hungary,2021-06-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2962,197,29,18250,Flight,Other,Jamie,Newton,1944-12-29,"0700 Heather View Apt. 797\nWeststad, IL 33725",29,Male,Egypt,2020-05-22
2973,3,26,19775,Car,Airbnb,Lauren,Lewis,2012-01-10,"061 Hanson Cliff\nGuzmanfurt, NE 34866",20,Non-Binary,Tanzania,2022-03-04
2976,181,18,28957,Roadtrip,Airbnb,Roy,Rodriguez,1991-07-21,"21399 Vasquez Estate Suite 310\nNew Maurice, M...",29,Non-Binary,Mauritius,2020-11-13
2977,6,8,11479,Bus,Resorts,Keith,Baker,1990-09-04,"32321 Wilson Landing Apt. 951\nStephensbury, A...",28,Non-Binary,Iceland,2020-10-22
2999,283,13,19865,Cruise,Airbnb,Tom,Fletcher,1990-03-20,908 Christina Junctions Apt. 546\nPerkinsville...,22,Non-Binary,Mozambique,2021-08-07

In [14]:
df2=df.loc[df['Age']<30]

In [15]:
df2

,Trip #no.,Duration,Cost of Travel(Entire Trip),Mode of Travel,Stay,First Name,Last Name,Date of Birth,Address,Age,Sex,Nationality,Date of Travel
1,288,5,29681,Car,Hotel,Patricia,Young,1923-09-25,716 Dominguez Row Suite 775\nSouth Tiffanyboro...,19,Female,Gabon,2021-09-04
6,173,8,16642,Flight,Airbnb,Debra,Mitchell,1927-02-17,"05543 Scott Mount Suite 815\nPriceland, VI 56675",25,Male,San Marino,2022-08-07
8,154,27,25299,Car,Airbnb,Jeffrey,Key,1913-02-13,"4725 Ferguson Hill Suite 157\nEriktown, PR 09538",25,Female,Kyrgyz Republic,2022-06-28
18,7,19,25750,Roadtrip,Other,Lisa,Smith,1993-09-19,Unit 7905 Box 2194\nDPO AE 84402,22,Transgender,France,2021-12-15
22,56,24,10551,Flight,Resorts,John,Johnson,1922-11-04,"43152 Deborah Pine Suite 123\nWest Andreland, ...",19,Transgender,Hungary,2021-06-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2962,197,29,18250,Flight,Other,Jamie,Newton,1944-12-29,"0700 Heather View Apt. 797\nWeststad, IL 33725",29,Male,Egypt,2020-05-22
2973,3,26,19775,Car,Airbnb,Lauren,Lewis,2012-01-10,"061 Hanson Cliff\nGuzmanfurt, NE 34866",20,Non-Binary,Tanzania,2022-03-04
2976,181,18,28957,Roadtrip,Airbnb,Roy,Rodriguez,1991-07-21,"21399 Vasquez Estate Suite 310\nNew Maurice, M...",29,Non-Binary,Mauritius,2020-11-13
2977,6,8,11479,Bus,Resorts,Keith,Baker,1990-09-04,"32321 Wilson Landing Apt. 951\nStephensbury, A...",28,Non-Binary,Iceland,2020-10-22
2999,283,13,19865,Cruise,Airbnb,Tom,Fletcher,1990-03-20,908 Christina Junctions Apt. 546\nPerkinsville...,22,Non-Binary,Mozambique,2021-08-07

In [18]:
df.loc[(df['Age']<30) & (df['Stay'] == "Hotel")]

,Trip #no.,Duration,Cost of Travel(Entire Trip),Mode of Travel,Stay,First Name,Last Name,Date of Birth,Address,Age,Sex,Nationality,Date of Travel
1,288,5,29681,Car,Hotel,Patricia,Young,1923-09-25,716 Dominguez Row Suite 775\nSouth Tiffanyboro...,19,Female,Gabon,2021-09-04
50,216,28,28339,Car,Hotel,Jeremy,Conrad,2015-08-05,"88823 Hill Point Apt. 589\nSouth Dakota, FM 76432",18,Male,Timor-Leste,2020-01-24
56,164,8,15728,Train,Hotel,Ronald,Ortiz,2011-10-07,USNS Schultz\nFPO AE 77732,22,Transgender,Malta,2022-03-14
71,256,11,17377,Bus,Hotel,Amy,Dixon,2003-12-14,"918 Cole Extensions Apt. 064\nJohnsonville, VT...",28,Transgender,Greenland,2021-05-30
90,257,10,5881,Train,Hotel,Charles,Holden,1970-07-24,"02951 Christine Unions Suite 351\nSmithmouth, ...",24,Transgender,Iceland,2023-08-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2810,174,1,22963,Bus,Hotel,Christopher,Walker,1916-10-22,"2212 Miller Fork Apt. 375\nNew Brianna, CA 59566",21,Female,Mongolia,2023-03-18
2819,73,24,13476,Cruise,Hotel,Paul,Love,2010-02-11,2726 Ortega Garden Suite 913\nChristopherburgh...,29,Male,Saint Martin,2023-08-12
2860,173,1,26676,Bus,Hotel,Joseph,Arnold,2010-08-22,"99254 Shawn Gateway\nNew Rebeccashire, LA 92577",26,Male,Norway,2023-06-22
2866,159,1,13803,Roadtrip,Hotel,Douglas,Thompson,1942-03-17,"819 Callahan Course\nJamiestad, PR 78512",26,Female,Saudi Arabia,2020-02-21
2899,47,3,15401,Flight,Hotel,Robert,Webster,1969-05-02,"1163 Jacob Square\nEast Darlene, IA 48611",23,Transgender,Saint Helena,2023-06-29

In [19]:
df3=df.loc[(df['Age']<30) & (df['Stay'] == "Hotel")]
df3

,Trip #no.,Duration,Cost of Travel(Entire Trip),Mode of Travel,Stay,First Name,Last Name,Date of Birth,Address,Age,Sex,Nationality,Date of Travel
1,288,5,29681,Car,Hotel,Patricia,Young,1923-09-25,716 Dominguez Row Suite 775\nSouth Tiffanyboro...,19,Female,Gabon,2021-09-04
50,216,28,28339,Car,Hotel,Jeremy,Conrad,2015-08-05,"88823 Hill Point Apt. 589\nSouth Dakota, FM 76432",18,Male,Timor-Leste,2020-01-24
56,164,8,15728,Train,Hotel,Ronald,Ortiz,2011-10-07,USNS Schultz\nFPO AE 77732,22,Transgender,Malta,2022-03-14
71,256,11,17377,Bus,Hotel,Amy,Dixon,2003-12-14,"918 Cole Extensions Apt. 064\nJohnsonville, VT...",28,Transgender,Greenland,2021-05-30
90,257,10,5881,Train,Hotel,Charles,Holden,1970-07-24,"02951 Christine Unions Suite 351\nSmithmouth, ...",24,Transgender,Iceland,2023-08-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2810,174,1,22963,Bus,Hotel,Christopher,Walker,1916-10-22,"2212 Miller Fork Apt. 375\nNew Brianna, CA 59566",21,Female,Mongolia,2023-03-18
2819,73,24,13476,Cruise,Hotel,Paul,Love,2010-02-11,2726 Ortega Garden Suite 913\nChristopherburgh...,29,Male,Saint Martin,2023-08-12
2860,173,1,26676,Bus,Hotel,Joseph,Arnold,2010-08-22,"99254 Shawn Gateway\nNew Rebeccashire, LA 92577",26,Male,Norway,2023-06-22
2866,159,1,13803,Roadtrip,Hotel,Douglas,Thompson,1942-03-17,"819 Callahan Course\nJamiestad, PR 78512",26,Female,Saudi Arabia,2020-02-21
2899,47,3,15401,Flight,Hotel,Robert,Webster,1969-05-02,"1163 Jacob Square\nEast Darlene, IA 48611",23,Transgender,Saint Helena,2023-06-29

In [22]:
df.loc[(df['Age']<30) & (df['Stay'] == "Hotel") & (df['Cost of Travel(Entire Trip)']<6000)]

,Trip #no.,Duration,Cost of Travel(Entire Trip),Mode of Travel,Stay,First Name,Last Name,Date of Birth,Address,Age,Sex,Nationality,Date of Travel
90,257,10,5881,Train,Hotel,Charles,Holden,1970-07-24,"02951 Christine Unions Suite 351\nSmithmouth, ...",24,Transgender,Iceland,2023-08-07
299,188,9,5233,Bus,Hotel,Brandon,Stafford,1983-10-02,"90656 Ramirez Street Suite 672\nNew Craig, KY ...",27,Female,Mauritius,2021-05-07
714,100,15,5601,Bus,Hotel,Julie,Young,1958-09-11,"3114 Le Locks\nPort Barbara, WV 13529",22,Female,Somalia,2022-07-22
1638,218,24,5744,Train,Hotel,Sean,Norman,1917-03-19,Unit 7075 Box 3564\nDPO AP 11017,20,Transgender,Taiwan,2021-10-06
1932,294,3,5648,Roadtrip,Hotel,Jessica,Payne,1948-01-13,"33945 Stephens Course Apt. 943\nAndrewfort, GA...",22,Female,Mauritius,2020-07-01
1936,221,25,5631,Train,Hotel,Jennifer,Miller,2012-04-23,"9821 Brent Bridge Apt. 109\nWest Robertton, ME...",29,Female,China,2022-09-28

In [23]:
df4=df.loc[(df['Age']<30) & (df['Stay'] == "Hotel") & (df['Cost of Travel(Entire Trip)']<6000)]

In [24]:
df4

,Trip #no.,Duration,Cost of Travel(Entire Trip),Mode of Travel,Stay,First Name,Last Name,Date of Birth,Address,Age,Sex,Nationality,Date of Travel
90,257,10,5881,Train,Hotel,Charles,Holden,1970-07-24,"02951 Christine Unions Suite 351\nSmithmouth, ...",24,Transgender,Iceland,2023-08-07
299,188,9,5233,Bus,Hotel,Brandon,Stafford,1983-10-02,"90656 Ramirez Street Suite 672\nNew Craig, KY ...",27,Female,Mauritius,2021-05-07
714,100,15,5601,Bus,Hotel,Julie,Young,1958-09-11,"3114 Le Locks\nPort Barbara, WV 13529",22,Female,Somalia,2022-07-22
1638,218,24,5744,Train,Hotel,Sean,Norman,1917-03-19,Unit 7075 Box 3564\nDPO AP 11017,20,Transgender,Taiwan,2021-10-06
1932,294,3,5648,Roadtrip,Hotel,Jessica,Payne,1948-01-13,"33945 Stephens Course Apt. 943\nAndrewfort, GA...",22,Female,Mauritius,2020-07-01
1936,221,25,5631,Train,Hotel,Jennifer,Miller,2012-04-23,"9821 Brent Bridge Apt. 109\nWest Robertton, ME...",29,Female,China,2022-09-28

This was so much fun! In Group A there were 598 tourists under the age of 30,in Group B there were 146 tourist who stayed in hotel and were under the age of 30, and finally in Group C there were 6 potentials and only 1 was from China and her name is **Jennifer Mille**r.